# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8da72a4190c0bd9d4cb186fa19760f500a564532c502569e553c529929e403822006215123fb9a690e0ea9d24c6cfccf43862d80f810a5438da6aed2e4120fe9

test:
  secret_key_base: 04c386565c465379865e4558e522ffeaa8dc9e81a5d0bf792b154cc86eb31ff816fb90a1893b87d9f54d5587552602026a31ac2acb614f3970d39dc9b4a834bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
